---
applications:
  - name: api
    instances: 2
    memory: 2G
    disk_quota: 1G
    stack: cflinuxfs4
    buildpacks:
      - python_buildpack
    path: ../
    routes:
      - route: fec-stage-api.app.cloud.gov
    services:
      - api-creds-stage
      - fec-api-elasticsearch
      - fec-elasticache-redis
      - fec-creds-stage
      - fec-s3-api
      - fec-s3-snapshot
    env:
      FEC_API_USE_PROXY: true
      FEC_API_RESTRICT_DOWNLOADS: true
      FEC_SHOW_TEST_F1: true
      APP_NAME: fec | api | stage
