---
path: ../
memory: 1500M # 1.5G
stack: cflinuxfs3
buildpack: python_buildpack
env:
  FEC_API_USE_PROXY: true
  FEC_API_RESTRICT_DOWNLOADS: true
  APP_NAME: fec | api | prod
  PRODUCTION: True
services:
  - fec-api-search56
  - fec-redis
  - fec-creds-prod
  - fec-s3-prod
routes:
  - route: fec-prod-api.app.cloud.gov
applications:
  - name: api
    instances: 10
    disk_quota: 1G
