plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

configurations.all {
    resolutionStrategy.force "io.netty:netty-handler:4.1.136.Final"
    resolutionStrategy.force "io.netty:netty-handler-proxy:4.1.136.Final"
    resolutionStrategy.force "io.netty:netty-codec-dns:4.1.136.Final"
    resolutionStrategy.force "io.netty:netty-codec-http:4.1.136.Final"
    resolutionStrategy.force "io.netty:netty-codec-http2:4.1.136.Final"
    resolutionStrategy.force "io.netty:netty-resolver-dns:4.1.136.Final"
    resolutionStrategy.force "io.projectreactor.netty:reactor-netty-http:1.2.18"
    resolutionStrategy.force "com.fasterxml.jackson.core:jackson-core:2.21.4"
    resolutionStrategy.force "org.apache.httpcomponents.core5:httpcore5-h2:5.4.3"
    resolutionStrategy.force "com.nimbusds:nimbus-jose-jwt:10.0.2"
}

dependencies {
    implementation group: "org.flywaydb", name: "flyway-gradle-plugin", version: "9.6.1"
    implementation "io.netty:netty-handler:4.1.136.Final"
    implementation "io.netty:netty-handler-proxy:4.1.136.Final"
    implementation "io.netty:netty-codec-dns:4.1.136.Final"
    implementation "io.netty:netty-codec-http:4.1.136.Final"
    implementation "io.netty:netty-codec-http2:4.1.136.Final"
    implementation "io.netty:netty-resolver-dns:4.1.136.Final"
    implementation "io.projectreactor.netty:reactor-netty-http:1.2.18"
    implementation "org.apache.httpcomponents.core5:httpcore5-h2:5.4.3"
    implementation "com.nimbusds:nimbus-jose-jwt:10.0.2"
    implementation (group: "org.flywaydb", name: "flyway-commandline", version: "13.0.0") {
        exclude group: "com.fasterxml.jackson.core", module: "jackson-databind"
        exclude group: "com.microsoft.sqlserver", module: "msql-jdbc"
        exclude group: "com.microsoft.azure", module: "msal4j"
        exclude group: "com.google.cloud", module: "google-cloud-storage"
        exclude group: "com.azure", module: "azure-identity"
        exclude group: "com.ing.data", module: "cassandra-jdbc-wrapper"
        exclude group: "org.flywaydb", module: "flyway-database-nc-cassandra"
        exclude group: "org.apache.commons", module: "commons-text"
        exclude group: "com.h2database", module: "h2"
        exclude group: "com.pivotal.jdbc", module: "greenplumdriver"
        exclude group: "net.sourceforge.jtds", module: "jtds"
	    exclude group: "mysql", module: "mysql-connector-java"
        exclude group: "org.apache.derby", module: "derby"
        exclude group: "org.apache.derby", module: "derbyclient"
        exclude group: "org.hsqldb", module: "hsqldb"
        exclude group: "org.mariadb.jdbc", module: "mariadb-java-client"
        exclude group: "org.xerial", module: "sqlite-jdbc"
        exclude group: "com.google.protobuf", module: "protobuf-java"
        exclude group: "com.google.guava", module: "guava"
        constraints {
	       implementation("org.postgresql:postgresql:42.6.0.jar")
           implementation("com.fasterxml.jackson.core:jackson-databind:2.22.1")
        }
    }
}

application {
    mainClass = 'org.flywaydb.commandline.Main'
}

task createJarsDir {
    def jars = file("$buildDir/jars")
    outputs.dir jars
    doLast {
        jars.mkdirs()
        new File(jars, "readme.txt").write("Empty file so that it gets copied")
    }
}

task createMigrationsDir {
    def migrations = file("$buildDir/migrations")
    outputs.dir migrations
    doLast {
        migrations.mkdirs()
        copy {
            from "../migrations"
            into migrations
        }
    }
}

task createRunScript {
    def run_scrip = file("$buildDir/bin")
    outputs.dir run_scrip
    doLast {
        run_scrip.mkdirs()
        copy {
            from "run.sh"
            into run_scrip
        }
    }
}

task copyPostgresJar(type: Copy) {
    into "$buildDir/drivers"
    from configurations.runtimeOnly
    include "postgres*.jar"
}

distZip.dependsOn(copyPostgresJar)

distributions {
    main {
        contents {
            from(createJarsDir) {
                into "jars"
            }
            from(copyPostgresJar) {
                into "drivers"
            }
            from(createMigrationsDir) {
                into "migrations"
            }
            from(createRunScript) {
                into "bin"
            }
        }
    }
}
