cmte = {
    'P': 'Presidential',
    'H': 'House',
    'S': 'Senate',
    'C': 'Communication Cost',
    'D': 'Delegate Committee',
    'E': 'Electioneering Communication',
    'I': 'Independent Expenditor (Person or Group)',
    'N': 'PAC - Nonqualified',
    'O': 'Independent Expenditure-Only (Super PACs)',
    'Q': 'PAC - Qualified',
    'U': 'Single Candidate Independent Expenditure',
    'V': 'PAC with Non-Contribution Account - Nonqualified',
    'W': 'PAC with Non-Contribution Account - Qualified',
    'X': 'Party - Nonqualified',
    'Y': 'Party - Qualified',
    'Z': 'National Party Nonfederal Account'
}
designation = {
    'A': 'Authorized by a candidate',
    'J': 'Joint fundraising committee',
    'P': 'Principal campaign committee',
    'U': 'Unauthorized',
    'B': 'Lobbyist/Registrant PAC',
    'D': 'Leadership PAC',
}
party = {
    'ACE': 'Ace Party',
    'AKI': 'Alaskan Independence Party',
    'AIC': 'American Independent Conservative',
    'AIP': 'American Independent Party',
    'AMP': 'American Party',
    'APF': "American People's Freedom Party",
    'AE': 'Americans Elect',
    'CIT': "Citizens' Party",
    'CMD': 'Commandments Party',
    'CMP': 'Commonwealth Party of the U.S.',
    'COM': 'Communist Party',
    'CNC': 'Concerned Citizens Party Of Connecticut',
    'CRV': 'Conservative Party',
    'CON': 'Constitution Party',
    'CST': 'Constitutional',
    'COU': 'Country',
    'DCG': 'D.C. Statehood Green Party',
    'DNL': 'Democratic -Nonpartisan League',
    'DEM': 'Democratic Party',
    'D/C': 'Democratic/Conservative',
    'DFL': 'Democratic-Farmer-Labor',
    'DGR': 'Desert Green Party',
    'FED': 'Federalist',
    'FLP': 'Freedom Labor Party',
    'FRE': 'Freedom Party',
    'GWP': 'George Wallace Party',
    'GRT': 'Grassroots',
    'GRE': 'Green Party',
    'GR': 'Green-Rainbow',
    'HRP': 'Human Rights Party',
    'IDP': 'Independence Party',
    'IND': 'Independent',
    'IAP': 'Independent American Party',
    'ICD': 'Independent Conservative Democratic',
    'IGR': 'Independent Green',
    'IP': 'Independent Party',
    'IDE': 'Independent Party of Delaware',
    'IGD': 'Industrial Government Party',
    'JCN': 'Jewish/Christian National',
    'JUS': 'Justice Party',
    'LRU': 'La Raza Unida',
    'LBR': 'Labor Party',
    'LFT': 'Less Federal Taxes',
    'LBL': 'Liberal Party',
    'LIB': 'Libertarian Party',
    'LBU': 'Liberty Union Party',
    'MTP': 'Mountain Party',
    'NDP': 'National Democratic Party',
    'NLP': 'Natural Law Party',
    'NA': 'New Alliance',
    'NJC': 'New Jersey Conservative Party',
    'NPP': 'New Progressive Party',
    'NPA': 'No Party Affiliation',
    'NOP': 'No Party Preference',
    'NNE': 'None',
    'N': 'Nonpartisan',
    'NON': 'Non-Party',
    'OE': 'One Earth Party',
    'OTH': 'Other',
    'PG': 'Pacific Green',
    'PSL': 'Party for Socialism and Liberation',
    'PAF': 'Peace And Freedom',
    'PFP': 'Peace And Freedom Party',
    'PFD': 'Peace Freedom Party',
    'POP': 'People Over Politics',
    'PPY': "People's Party",
    'PCH': 'Personal Choice Party',
    'PPD': 'Popular Democratic Party',
    'PRO': 'Progressive Party',
    'NAP': 'Prohibition Party',
    'PRI': 'Puerto Rican Independence Party',
    'RUP': 'Raza Unida Party',
    'REF': 'Reform Party',
    'REP': 'Republican Party',
    'RES': 'Resource Party',
    'RTL': 'Right To Life',
    'SEP': 'Socialist Equality Party',
    'SLP': 'Socialist Labor Party',
    'SUS': 'Socialist Party',
    'SOC': 'Socialist Party U.S.A.',
    'SWP': 'Socialist Workers Party',
    'TX': 'Taxpayers',
    'TWR': 'Taxpayers Without Representation',
    'TEA': 'Tea Party',
    'THD': 'Theo-Democratic',
    'LAB': 'U.S. Labor Party',
    'USP': "U.S. People's Party",
    'UST': 'U.S. Taxpayers Party',
    'UN': 'Unaffiliated',
    'UC': 'United Citizen',
    'UNI': 'United Party',
    'UNK': 'Unknown',
    'VET': 'Veterans Party',
    'WTP': 'We the People',
    'W': 'Write-In'
}
status = {
    'C': 'candidate',
    'F': 'future_candidate',
    'N': 'not_yet_candidate',
    'P': 'prior_candidate'
}
ici = {'C': 'challenger', 'I': 'incumbent', 'O': 'open_seat'}
